### ISSUE TITLE
Grafana - Incorrect query for Request Count 

### ISSUE THREAD

**Issue by daveharris1** [VIP-Logic/NBomber#694] opened 2024-05-14 12:50 UTC
The following issues has been raised after talking with Anton Moldovan.

NBomber NuGet package version: 5.6.0
NBomber.Sinks.InfluxDB NuGet package version: 5.0.2

When Running NBomber via AutoCluster in a distributed manner, the generated 'Session' Coordinator reports i.e csv, HTML5 report looks to be duplicating the request count information.

This has been seen after every distributed run and doesn't seem to be affect by agent count. The data generated in the reports is at odds with what is reported via the Grafana dash board.

Example Bombing run Grafana output (after test completion):

![image](https://github.com/PragmaticFlow/NBomber/assets/12339745/7896cdf3-bd12-4ac8-9972-4e2c73da5aae)

Example of the HTML5 report showing what looks to be the duplication of requests and RPS data along with the fact the data doesn't match the Grafana output above:

![image](https://github.com/PragmaticFlow/NBomber/assets/12339745/2ff38331-24c0-480c-874c-1039bf147461)

**Comment by AntyaDev** [comment] 2024-05-31 19:10
Hi @daveharris1 ,

Are you sure that the HTML report was taken from the Coordinator? I have tried to reproduce this behavior several times locally but have had no luck so far.

**Comment by AntyaDev** [comment] 2024-05-31 19:40
![image](https://github.com/PragmaticFlow/NBomber/assets/1080518/c3985750-3d4d-4b2a-b561-d2dd6942bb3c)

![image](https://github.com/PragmaticFlow/NBomber/assets/1080518/81718890-a8e4-45f4-bd60-ae771eb7e2fd)

**Comment by AntyaDev** [comment] 2024-05-31 19:41
I have tried to run 3 min load test with cluster of 2-3 nodes but the results are always consistent.

**Comment by daveharris1** [comment] 2024-06-04 08:08
> Hi @daveharris1 ,
> 
> Are you sure that the HTML report was taken from the Coordinator? I have tried to reproduce this behavior several times locally but have had no luck so far.

Yes this is the Coordinator. This is from the generated txt that is in the same 'session' folder generated for the Coordinator with the HTML report:

![image](https://github.com/PragmaticFlow/NBomber/assets/12339745/9afcccdd-b8f7-4e99-93d3-3a748f7484e0)

![image](https://github.com/PragmaticFlow/NBomber/assets/12339745/7b814648-7cf0-4187-88da-76fb68122363)

As mentioned on the other issues I have open, we do not wait for the scenario to complete but exit the test early via:

`void StopCurrentTest(string reason);`
(https://nbomber.com/docs/using-nbomber/basic-api/scenario/#scenario-context)

I am also using multiple steps in the test via https://nbomber.com/docs/using-nbomber/basic-api/step

The latest run again shows a mismatch between the report generated data and what is shown in the Grafana dashboard. I have noted the RPS looks to match between the two sources.

![image](https://github.com/PragmaticFlow/NBomber/assets/12339745/dfdc4010-8f68-49ca-ae4b-2979b8f356da)

![image](https://github.com/PragmaticFlow/NBomber/assets/12339745/01242b37-afb3-4b55-ba21-7394b4e42184)

**Comment by AntyaDev** [comment] 2024-06-19 08:54
Hi @daveharris1 
It seems that the issue was caused by an incorrect query in the Grafana Dashboard but not NBomber.
https://github.com/PragmaticFlow/NBomber.Grafana/commit/17c3f27a638e9b075351e28aecc44693d08be4d4

Fixed in NBomber [5.7.0-beta.7](https://www.nuget.org/packages/NBomber/5.7.0-beta.7)
Also, you need to get the latest NBomber Garfana dashboards.

**Closed as completed** 2024-06-20 11:40 UTC
Labels: bug, 5.7
